function contour_map = ICCP_Parse_Contourc(C)
% Name: ICCP_Parse_Contourc
% Description: Parses the output matrix (C) from MATLAB's 'contourc' 
%              function into a containers.Map for efficient lookups.
% Parameters:
%   C: (2 x M) The contour matrix generated by contourc.
% Output:
%   contour_map: (containers.Map) A map where each key is a contour
%                level (double) and its value is an (K x 2) matrix
%                of [x, y] coordinates for that contour level.
% Example:
%   C = contourc(X, Y, Z, [10, 20]);
%   my_map = ICCP_Parse_Contourc(C);
%   level_10_points = my_map(10);

% Initialize the map
contour_map = containers.Map('KeyType', 'double', 'ValueType', 'any');

if isempty(C)
    return;
end

idx = 1;
while idx < size(C, 2)
    % 1. Read segment header
    level = C(1, idx); % Magnetic value for this contour
    N = C(2, idx);     % Number of points in this segment
    
    % 2. Determine coordinate indices for this segment
    start_col = idx + 1;
    end_col = idx + N;
    
    % 3. Extract coordinates
    x_coords = C(1, start_col:end_col);
    y_coords = C(2, start_col:end_col);
    
    segment_points = [x_coords', y_coords'];
    
    % 4. Add these points to the Map
    if isKey(contour_map, level)
        % If this magnetic value (key) already exists, append points
        contour_map(level) = [contour_map(level); segment_points];
    else
        % Otherwise, create a new entry
        contour_map(level) = segment_points;
    end
    
    % 5. Move to the next segment
    idx = end_col + 1;
end

end
